CC = gcc
CFLAGS = -Wall -Wextra -Werror
HEADERS = -I header.h
NAME = rush-2
SRCS = additional_functions.c main.c rushfunctions.c

all:
	$(CC) $(CFLAGS) -o $(NAME) $(SRCS) $(HEADERS)

clean:

fclean:
	rm rush-2
